/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-09-09 03:36:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.adminowner.owner;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import review.model.vo.Review;
import adminowner.admin.model.vo.PageInfo;
import java.util.ArrayList;
import member.model.vo.Member;
import accommodation.model.vo.Acm;
import accommodation.model.vo.AcmImg;

public final class psManagement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/adminowner/owner/../../../views/adminowner/common/ownerSidebar.jsp", Long.valueOf(1567677322098L));
    _jspx_dependants.put("/views/adminowner/owner/../../../views/adminowner/common/footer.jsp", Long.valueOf(1567436039424L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("accommodation.model.vo.AcmImg");
    _jspx_imports_classes.add("adminowner.admin.model.vo.PageInfo");
    _jspx_imports_classes.add("accommodation.model.vo.Acm");
    _jspx_imports_classes.add("review.model.vo.Review");
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

	ArrayList<Review> rList = (ArrayList<Review>)request.getAttribute("rList");
	PageInfo pi = (PageInfo)request.getAttribute("pi");
	
	int listCount = pi.getListCount();
	int currentPage = pi.getCurrentPage();
	int maxPage = pi.getMaxPage();
	int startPage = pi.getStartPage();
	int endPage = pi.getEndPage();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("  ul.sidebar-menu li a.active3, ul.sidebar-menu li a:hover, ul.sidebar-menu li a:focus {\r\n");
      out.write("    background: #fd7e14;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    display: block;\r\n");
      out.write("    -webkit-transition: all 0.3s ease;\r\n");
      out.write("    -moz-transition: all 0.3s ease;\r\n");
      out.write("    -o-transition: all 0.3s ease;\r\n");
      out.write("    -ms-transition: all 0.3s ease;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".profile-pic img {\r\n");
      out.write("    width: 60%;\r\n");
      out.write("    height: 50%;\r\n");
      out.write("    border: 10px solid #f1f2f7;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("#reviewTable td{\r\n");
      out.write("cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("#reviewTable th{\r\n");
      out.write("cursor : default;\r\n");
      out.write("}\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
  Member loginUser = (Member)session.getAttribute("loginUser");
	ArrayList<AcmImg> acmImgList = (ArrayList<AcmImg>)session.getAttribute("acmImgList");
	Acm acm = (Acm)session.getAttribute("acm");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("  ul.sidebar-menu li a.active, ul.sidebar-menu li a:hover, ul.sidebar-menu li a:focus {\r\n");
      out.write("    background: #fd7e14;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    display: block;\r\n");
      out.write("    -webkit-transition: all 0.3s ease;\r\n");
      out.write("    -moz-transition: all 0.3s ease;\r\n");
      out.write("    -o-transition: all 0.3s ease;\r\n");
      out.write("    -ms-transition: all 0.3s ease;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("ul.sidebar-menu li ul.sub li.active a {\r\n");
      out.write("    color: #fd7e14;\r\n");
      out.write("    -webkit-transition: all 0.3s ease;\r\n");
      out.write("    -moz-transition: all 0.3s ease;\r\n");
      out.write("    -o-transition: all 0.3s ease;\r\n");
      out.write("    -ms-transition: all 0.3s ease;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("    display: block;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("a{\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("  </style>\r\n");
      out.write("  <!-- 아이콘 -->\r\n");
      out.write("  <link href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/adminowner/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("  <link href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/adminowner/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\r\n");
      out.write("  \r\n");
      out.write("  <!-- jquery 연결 -->\r\n");
      out.write("  <script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/adminowner/lib/fullcalendar/jquery.min.js\"></script>\r\n");
      out.write("  <!-- 부트스트랩 css -->\r\n");
      out.write("  <link href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/adminowner/lib/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!--아이콘 css-->\r\n");
      out.write("  <link href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/adminowner/lib/font-awesome/css/font-awesome.css\" rel=\"stylesheet\" />\r\n");
      out.write("  <!-- 전체 디자인 -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/adminowner/lib/advanced-datatable/css/DT_bootstrap.css\" />\r\n");
      out.write("  <link href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/adminowner/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- 반응형 -->\r\n");
      out.write("  <link href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/adminowner/css/style-responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/adminowner/lib/chart-master/Chart.js\"></script>\r\n");
      out.write("  <!-- 타이틀 옆에있는 버튼 3개 -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/adminowner/lib/advanced-datatable/js/DT_bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <!--header start-->\r\n");
      out.write("    <header class=\"header black-bg\">\r\n");
      out.write("      <div class=\"sidebar-toggle-box\">\r\n");
      out.write("        <div class=\"fa fa-bars tooltips\" data-placement=\"right\" data-original-title=\"확대 / 축소\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!--logo start-->\r\n");
      out.write("      <a href=\"");
      out.print( request.getContextPath() );
      out.write("/ownerIndex.ow\" class=\"logo\"><b>Come To<span> Jeju</span></b></a>\r\n");
      out.write("      <!--logo end-->\r\n");
      out.write("<!--       <div class=\"nav notify-row\" id=\"top_menu\">\r\n");
      out.write("         notification start\r\n");
      out.write("        <ul class=\"nav top-menu\">\r\n");
      out.write("          settings start\r\n");
      out.write("          <li class=\"dropdown\">\r\n");
      out.write("            <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"index.html#\">\r\n");
      out.write("              <i class=\"fa fa-tasks\"></i>\r\n");
      out.write("              <span class=\"badge bg-theme\">4</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            <ul class=\"dropdown-menu extended tasks-bar\">\r\n");
      out.write("              <div class=\"notify-arrow notify-arrow-green\"></div>\r\n");
      out.write("              <li>\r\n");
      out.write("                <p class=\"green\">You have 4 pending tasks</p>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"index.html#\">\r\n");
      out.write("                  <div class=\"task-info\">\r\n");
      out.write("                    <div class=\"desc\">Dashio Admin Panel</div>\r\n");
      out.write("                    <div class=\"percent\">40%</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"progress progress-striped\">\r\n");
      out.write("                    <div class=\"progress-bar progress-bar-success\" role=\"progressbar\" aria-valuenow=\"40\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 40%\">\r\n");
      out.write("                      <span class=\"sr-only\">40% Complete (success)</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"index.html#\">\r\n");
      out.write("                  <div class=\"task-info\">\r\n");
      out.write("                    <div class=\"desc\">Database Update</div>\r\n");
      out.write("                    <div class=\"percent\">60%</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"progress progress-striped\">\r\n");
      out.write("                    <div class=\"progress-bar progress-bar-warning\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 60%\">\r\n");
      out.write("                      <span class=\"sr-only\">60% Complete (warning)</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"index.html#\">\r\n");
      out.write("                  <div class=\"task-info\">\r\n");
      out.write("                    <div class=\"desc\">Product Development</div>\r\n");
      out.write("                    <div class=\"percent\">80%</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"progress progress-striped\">\r\n");
      out.write("                    <div class=\"progress-bar progress-bar-info\" role=\"progressbar\" aria-valuenow=\"80\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 80%\">\r\n");
      out.write("                      <span class=\"sr-only\">80% Complete</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"index.html#\">\r\n");
      out.write("                  <div class=\"task-info\">\r\n");
      out.write("                    <div class=\"desc\">Payments Sent</div>\r\n");
      out.write("                    <div class=\"percent\">70%</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"progress progress-striped\">\r\n");
      out.write("                    <div class=\"progress-bar progress-bar-danger\" role=\"progressbar\" aria-valuenow=\"70\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 70%\">\r\n");
      out.write("                      <span class=\"sr-only\">70% Complete (Important)</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"external\">\r\n");
      out.write("                <a href=\"#\">See All Tasks</a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          settings end\r\n");
      out.write("          inbox dropdown start\r\n");
      out.write("          <li id=\"header_inbox_bar\" class=\"dropdown\">\r\n");
      out.write("            <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"index.html#\">\r\n");
      out.write("              <i class=\"fa fa-envelope-o\"></i>\r\n");
      out.write("              <span class=\"badge bg-theme\">5</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            <ul class=\"dropdown-menu extended inbox\">\r\n");
      out.write("              <div class=\"notify-arrow notify-arrow-green\"></div>\r\n");
      out.write("              <li>\r\n");
      out.write("                <p class=\"green\">You have 5 new messages</p>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"index.html#\">\r\n");
      out.write("                  <span class=\"photo\"><img alt=\"avatar\" src=\"img/ui-zac.jpg\"></span>\r\n");
      out.write("                  <span class=\"subject\">\r\n");
      out.write("                  <span class=\"from\">Zac Snider</span>\r\n");
      out.write("                  <span class=\"time\">Just now</span>\r\n");
      out.write("                  </span>\r\n");
      out.write("                  <span class=\"message\">\r\n");
      out.write("                  Hi mate, how is everything?\r\n");
      out.write("                  </span>\r\n");
      out.write("                  </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"index.html#\">\r\n");
      out.write("                  <span class=\"photo\"><img alt=\"avatar\" src=\"img/ui-divya.jpg\"></span>\r\n");
      out.write("                  <span class=\"subject\">\r\n");
      out.write("                  <span class=\"from\">Divya Manian</span>\r\n");
      out.write("                  <span class=\"time\">40 mins.</span>\r\n");
      out.write("                  </span>\r\n");
      out.write("                  <span class=\"message\">\r\n");
      out.write("                  Hi, I need your help with this.\r\n");
      out.write("                  </span>\r\n");
      out.write("                  </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"index.html#\">\r\n");
      out.write("                  <span class=\"photo\"><img alt=\"avatar\" src=\"img/ui-danro.jpg\"></span>\r\n");
      out.write("                  <span class=\"subject\">\r\n");
      out.write("                  <span class=\"from\">Dan Rogers</span>\r\n");
      out.write("                  <span class=\"time\">2 hrs.</span>\r\n");
      out.write("                  </span>\r\n");
      out.write("                  <span class=\"message\">\r\n");
      out.write("                  Love your new Dashboard.\r\n");
      out.write("                  </span>\r\n");
      out.write("                  </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"index.html#\">\r\n");
      out.write("                  <span class=\"photo\"><img alt=\"avatar\" src=\"img/ui-sherman.jpg\"></span>\r\n");
      out.write("                  <span class=\"subject\">\r\n");
      out.write("                  <span class=\"from\">Dj Sherman</span>\r\n");
      out.write("                  <span class=\"time\">4 hrs.</span>\r\n");
      out.write("                  </span>\r\n");
      out.write("                  <span class=\"message\">\r\n");
      out.write("                  Please, answer asap.\r\n");
      out.write("                  </span>\r\n");
      out.write("                  </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"index.html#\">See all messages</a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          inbox dropdown end\r\n");
      out.write("          notification dropdown start\r\n");
      out.write("          <li id=\"header_notification_bar\" class=\"dropdown\">\r\n");
      out.write("            <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"index.html#\">\r\n");
      out.write("              <i class=\"fa fa-bell-o\"></i>\r\n");
      out.write("              <span class=\"badge bg-warning\">7</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            <ul class=\"dropdown-menu extended notification\">\r\n");
      out.write("              <div class=\"notify-arrow notify-arrow-yellow\"></div>\r\n");
      out.write("              <li>\r\n");
      out.write("                <p class=\"yellow\">You have 7 new notifications</p>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"index.html#\">\r\n");
      out.write("                  <span class=\"label label-danger\"><i class=\"fa fa-bolt\"></i></span>\r\n");
      out.write("                  Server Overloaded.\r\n");
      out.write("                  <span class=\"small italic\">4 mins.</span>\r\n");
      out.write("                  </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"index.html#\">\r\n");
      out.write("                  <span class=\"label label-warning\"><i class=\"fa fa-bell\"></i></span>\r\n");
      out.write("                  Memory #2 Not Responding.\r\n");
      out.write("                  <span class=\"small italic\">30 mins.</span>\r\n");
      out.write("                  </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"index.html#\">\r\n");
      out.write("                  <span class=\"label label-danger\"><i class=\"fa fa-bolt\"></i></span>\r\n");
      out.write("                  Disk Space Reached 85%.\r\n");
      out.write("                  <span class=\"small italic\">2 hrs.</span>\r\n");
      out.write("                  </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"index.html#\">\r\n");
      out.write("                  <span class=\"label label-success\"><i class=\"fa fa-plus\"></i></span>\r\n");
      out.write("                  New User Registered.\r\n");
      out.write("                  <span class=\"small italic\">3 hrs.</span>\r\n");
      out.write("                  </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"index.html#\">See all notifications</a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          notification dropdown end\r\n");
      out.write("        </ul>\r\n");
      out.write("         notification end\r\n");
      out.write("      </div> -->\r\n");
      out.write("      <div class=\"top-menu\">\r\n");
      out.write("        <ul class=\"nav pull-right top-menu\">\r\n");
      out.write("          <li><a class=\"logout\" onclick=\"logout();\">Logout</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!--header end-->\r\n");
      out.write("    <!-- **********************************************************************************************************************************************************\r\n");
      out.write("        MAIN SIDEBAR MENU\r\n");
      out.write("        *********************************************************************************************************************************************************** -->\r\n");
      out.write("    <!--sidebar start-->\r\n");
      out.write("    <aside>\r\n");
      out.write("        <div id=\"sidebar\" class=\"nav-collapse \">\r\n");
      out.write("          <!-- sidebar menu start-->\r\n");
      out.write("          <ul class=\"sidebar-menu\" id=\"nav-accordion\">\r\n");
      out.write("            <p class=\"centered\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/page.ow\"><img src=\"");
      out.print(acmImgList.get(0).getImgPath());
      out.write("\" width=\"100%\"></a></p>\r\n");
      out.write("            <h5 class=\"centered\">  ");
      out.print( acm.getAcmName() );
      out.write("</h5>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a class=\"active1\" onclick=\"goDashBoard();\">\r\n");
      out.write("                <i class=\"fa fa-dashboard\"></i>\r\n");
      out.write("                <span>Dashboard</span>\r\n");
      out.write("               </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("            <a class=\"active2\" onclick=\"goManagement();\">\r\n");
      out.write("                <i class=\"fa fa-calendar\"></i>\r\n");
      out.write("                <span>숙소 예약 관리</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("            <a class=\"active3\" onclick=\"goPsManagement();\">\r\n");
      out.write("                <i class=\"fa fa-comment-o\"></i>\r\n");
      out.write("                <span>숙소 후기 관리</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <li>\r\n");
      out.write("            <a class=\"active4\" onclick=\"goChartManagement();\">\r\n");
      out.write("                <i class=\"fa fa-users\"></i>\r\n");
      out.write("                <span>숙소 통계 관리</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a class=\"active5\" onclick=\"goPowerMoney();\">\r\n");
      out.write("                  <i class=\"fa fa-bolt\"></i>\r\n");
      out.write("                  <span>파워 등록 !</span>\r\n");
      out.write("                  <!-- <span class=\"label label-theme pull-right mail-info\">2</span> -->\r\n");
      out.write("                  </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a class=\"active6\" onclick=\"goInquiry();\">\r\n");
      out.write("                  <i class=\"fa fa-envelope\"></i>\r\n");
      out.write("                  <span>문의하기</span>\r\n");
      out.write("                  <!-- <span class=\"label label-theme pull-right mail-info\">2</span> -->\r\n");
      out.write("                  </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <!-- sidebar menu end-->\r\n");
      out.write("        </div>\r\n");
      out.write("      </aside>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("    <!--sidebar end-->\r\n");
      out.write("  <!-- js placed at the end of the document so the pages load faster -->\r\n");
      out.write("\r\n");
      out.write("  <script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/adminowner/lib/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- 숙소 관리 눌렀을 때 테이블 토글되는 스크립트 -->\r\n");
      out.write("  <script class=\"include\" type=\"text/javascript\" src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/adminowner/lib/jquery.dcjqaccordion.2.7.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/adminowner/lib/jquery.scrollTo.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/adminowner/lib/jquery.nicescroll.js\" type=\"text/javascript\"></script>\r\n");
      out.write("  <script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/adminowner/lib/jquery.sparkline.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" language=\"javascript\" src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/adminowner/lib/advanced-datatable/js/jquery.dataTables.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/adminowner/lib/advanced-datatable/js/DT_bootstrap.js\"></script>\r\n");
      out.write("  <!--common script for all pages-->\r\n");
      out.write("  <script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/adminowner/lib/common-scripts.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/adminowner/lib/gritter/js/jquery.gritter.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/adminowner/lib/gritter-conf.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <script>\r\n");
      out.write("  \tfunction goDashBoard(){\r\n");
      out.write("  \t\tlocation.href = \"");
      out.print( request.getContextPath() );
      out.write("/page.ow\";\r\n");
      out.write("  \t}\r\n");
      out.write("  \tfunction goManagement(){\r\n");
      out.write("  \t\tlocation.href =\"");
      out.print( request.getContextPath() );
      out.write("/management.ow\";\r\n");
      out.write("  \t}\r\n");
      out.write("  \tfunction goPsManagement(){\r\n");
      out.write("  \t\tlocation.href =\"");
      out.print( request.getContextPath() );
      out.write("/psManagement.ow\";\r\n");
      out.write("  \t}\r\n");
      out.write("  \tfunction goChartManagement(){\r\n");
      out.write("  \t\tlocation.href =\"");
      out.print( request.getContextPath() );
      out.write("/chartManagement.ow\";\r\n");
      out.write("  \t}\r\n");
      out.write("  \tfunction goPowerMoney(){\r\n");
      out.write("  \t\tlocation.href =\"");
      out.print( request.getContextPath() );
      out.write("/powerMoney.ow\";\r\n");
      out.write("  \t}\r\n");
      out.write("  \tfunction goInquiry(){\r\n");
      out.write("  \t\tlocation.href =\"");
      out.print( request.getContextPath() );
      out.write("/inquiry.ow\";\r\n");
      out.write("  \t}\r\n");
      out.write("  \tfunction logout() {\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/logout.me\";\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<section id=\"main-content\">\r\n");
      out.write("\t\t<section class=\"wrapper site-min-height\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row mt\">\r\n");
      out.write("              <div class=\"col-lg-12\">\r\n");
      out.write("                <div class=\"row content-panel\">\r\n");
      out.write("                  <div class=\"col-md-4 profile-text mt mb centered\">\r\n");
      out.write("                    <div class=\"right-divider hidden-sm hidden-xs\">\r\n");
      out.write("                      <h4>");
      out.print( loginUser.getMemId() );
      out.write("</h4>\r\n");
      out.write("                      <h6>ID</h6>\r\n");
      out.write("                      <h4>");
      out.print( loginUser.getMemName());
      out.write("</h4>\r\n");
      out.write("                      <h6>NAME</h6>\r\n");
      out.write("                      <h4>");
      out.print( acm.getAcmPhone() );
      out.write("</h4>\r\n");
      out.write("                      <h6>PHONE</h6>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!-- /col-md-4 -->\r\n");
      out.write("                  <div class=\"col-md-4 profile-text\">\r\n");
      out.write("                    <h3>");
      out.print( acm.getAcmName() );
      out.write("</h3>\r\n");
      out.write("                    <h6>");
      out.print( loginUser.getMemName() );
      out.write("님 환영합니다</h6>\r\n");
      out.write("                    <p>COME TO JEJU를 이용해주셔서 감사합니다.<br>사용하시다가 불편한 점이나 개선할 점을<br> 문의해주시면 최대한 빠르게 조치하겠습니다.</p>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <p><button class=\"btn btn-theme\" onclick=\"goInquiry();\"><i class=\"fa fa-envelope\"></i> 문의하기</button></p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!-- /col-md-4 -->\r\n");
      out.write("                  <div class=\"col-md-4 centered\">\r\n");
      out.write("                    <div class=\"profile-pic\">\r\n");
      out.write("                      <p><img src=\"");
      out.print( acmImgList.get(0).getImgPath());
      out.write("\"></p>\r\n");
      out.write("                      <p>\r\n");
      out.write("<!--                         <button class=\"btn btn-theme\"><i class=\"fa fa-check\"></i> Follow</button>\r\n");
      out.write("                        <button class=\"btn btn-theme02\">Add</button> -->\r\n");
      out.write("                      </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!-- /col-md-4 -->\r\n");
      out.write("                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<div class=\"col-lg-12 mt\">\r\n");
      out.write("\t\t\t\t<div class=\"row content-panel\">\r\n");
      out.write("\t\t\t<h3>\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-angle-right\"></i> 리뷰 조회\r\n");
      out.write("\t\t\t</h3>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t<table id=\"reviewTable\" class=\"table table-bordered\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr id=\"tr1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"width:50px;\">번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"width:700px;\">리뷰제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>숙소</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>점수</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>작성자</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>예약번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>작성일</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t");
if(rList.isEmpty()){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr><td colspan=\"7\" text-align=\"center\">조회된 리뷰가 없습니다.</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
for(Review i: rList){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(i.getReviewNum() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(i.getReviewTitle() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(i.getAcmName() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(i.getReviewScore() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(i.getMemName() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(i.getReservNum() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(i.getReviewDate() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<div class=\"pagingArea\" align=\"right\">\r\n");
      out.write("\t\t\t\t\t");
if(currentPage == 1){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-default\" disabled> &lt; previous </button>\r\n");
      out.write("\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-default\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/psManagement.ow?currentPage=");
      out.print(currentPage-1);
      out.write("'\">&lt; previous</button>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
for(int p = startPage; p <= endPage; p++){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
if(p == currentPage){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-warning\" disabled> ");
      out.print( p );
      out.write(" </button>\r\n");
      out.write("\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/psManagement.ow?currentPage=");
      out.print( p );
      out.write("'\"> ");
      out.print( p );
      out.write(" </button>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
if(currentPage == maxPage){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-default\" disabled> next &gt; </button>\r\n");
      out.write("\t\t\t\t\t");
}else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-default\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/psManagement.ow?currentPage=");
      out.print( currentPage+1 );
      out.write("'\">next &gt;</button>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\"#reviewTable td\").click(function(){\r\n");
      out.write("\t\t\tvar rNum = $(this).parent().children().eq(0).text();\r\n");
      out.write("\t\t\tconsole.log(rNum);\r\n");
      out.write("\t\t\tlocation.href =\"");
      out.print( request.getContextPath() );
      out.write("/reviewDetail.ow?rNum=\" +rNum;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer class=\"site-footer\">\r\n");
      out.write("      <div class=\"text-center\">\r\n");
      out.write("        <p>\r\n");
      out.write("          &copy; Copyrights <strong>Dashio</strong>. All Rights Reserved\r\n");
      out.write("        </p>\r\n");
      out.write("        <div class=\"credits\">\r\n");
      out.write("          Created with Dashio template by <a href=\"https://templatemag.com/\">TemplateMag</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a href=\"index.html#\" class=\"go-top\">\r\n");
      out.write("          <i class=\"fa fa-angle-up\"></i>\r\n");
      out.write("          </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
