/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-08-14 05:27:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.searchResult;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class searchResult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/searchResult/../main/footer.jsp", Long.valueOf(1565086014000L));
    _jspx_dependants.put("/views/searchResult/../main/header.jsp", Long.valueOf(1565181778000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/animate.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/aos.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/bootstrap-datepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/jquery.timepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/fancybox.min.css\">      \r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/fonts/ionicons/css/ionicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/fonts/fontawesome/css/font-awesome.min.css\">\r\n");
      out.write("<!-- Theme Style -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* The Modal (background) */\r\n");
      out.write("          .popModal {\r\n");
      out.write("             display: none; /* Hidden by default */\r\n");
      out.write("             position: fixed; /* Stay in place */\r\n");
      out.write("             z-index: 2; /* Sit on top */\r\n");
      out.write("             left: 0;\r\n");
      out.write("             top: 0;\r\n");
      out.write("             width: 100%; /* Full width */\r\n");
      out.write("             height: 100%; /* Full height */\r\n");
      out.write("             overflow: hidden; /* Enable scroll if needed */\r\n");
      out.write("             background-color: rgb(0,0,0); /* Fallback color */\r\n");
      out.write("             background-color: rgba(0,0,0,0.4); /* Black w/ opacity */\r\n");
      out.write("         }\r\n");
      out.write("     \r\n");
      out.write("         /* Modal Content/Box */\r\n");
      out.write("         .modal-content {\r\n");
      out.write("             background-color: #fefefe;\r\n");
      out.write("             margin: 10% auto; /* 15% from the top and centered */\r\n");
      out.write("             padding: 20px;\r\n");
      out.write("             border: 1px solid #888;\r\n");
      out.write("             /* width: 30%; */ /* Could be more or less, depending on screen size */\r\n");
      out.write("             width:745px;\r\n");
      out.write("        \t height:450px;                        \r\n");
      out.write("         }\r\n");
      out.write("         /* The Close Button */\r\n");
      out.write("         .close {\r\n");
      out.write("             color: #aaa;\r\n");
      out.write("             float: right;\r\n");
      out.write("             font-size: 28px;\r\n");
      out.write("             font-weight: bold;\r\n");
      out.write("             text-align: right;\r\n");
      out.write("         }\r\n");
      out.write("         .close:hover,\r\n");
      out.write("         .close:focus {\r\n");
      out.write("             color: black;\r\n");
      out.write("             text-decoration: none;\r\n");
      out.write("             cursor: pointer;\r\n");
      out.write("         }\r\n");
      out.write("         .nav-item{\r\n");
      out.write("           cursor: pointer;\r\n");
      out.write("         }\r\n");
      out.write("         #logoutBtn{\r\n");
      out.write("         \tdisplay: none;\r\n");
      out.write("         }\r\n");
      out.write("         aside {\r\n");
      out.write("           float: left;\r\n");
      out.write("         }\r\n");
      out.write("         .star{\r\n");
      out.write("           color:gold;\r\n");
      out.write("           font-size: 20px;\r\n");
      out.write("         }\r\n");
      out.write("         .searchForm{\r\n");
      out.write("           border: 1px solid lightgray;\r\n");
      out.write("           width: 100%;\r\n");
      out.write("         }\r\n");
      out.write("         .result{\r\n");
      out.write("          border: 1px solid lightgray;\r\n");
      out.write("          width: 85%;\r\n");
      out.write("         }\r\n");
      out.write("         .searchPhoto{\r\n");
      out.write("          border: 1px solid lightgray;\r\n");
      out.write("          width: 300px;\r\n");
      out.write("          height: 200px;\r\n");
      out.write("         }\r\n");
      out.write("         .test{\r\n");
      out.write("          border: 1px solid lightgray;\r\n");
      out.write("         }\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         li{\r\n");
      out.write("            list-style-type: none;\r\n");
      out.write("        }\r\n");
      out.write("        .test{\r\n");
      out.write("            border: 1px solid lightgray;\r\n");
      out.write("        }\r\n");
      out.write("        .aa{\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        .resultWrap{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 250px;\r\n");
      out.write("        }\r\n");
      out.write("        .d1{\r\n");
      out.write("            width: 75%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .d2{\r\n");
      out.write("            width: 25%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }        \r\n");
      out.write("        .d3{\r\n");
      out.write("            height: 20%;\r\n");
      out.write("        }\r\n");
      out.write("        .d4{\r\n");
      out.write("            height: 80%;\r\n");
      out.write("        }\r\n");
      out.write("        .d5{\r\n");
      out.write("            width: 50%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            padding-top: 0px;\r\n");
      out.write("        }\r\n");
      out.write("        .d6{\r\n");
      out.write("            width: 50%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .d7{\r\n");
      out.write("        \theight:70%\r\n");
      out.write("        }\r\n");
      out.write("        .d8{\r\n");
      out.write("        \theight: 30%;\r\n");
      out.write("        \ttext-align:center;\r\n");
      out.write("        }\r\n");
      out.write("        .imgDiv{\r\n");
      out.write("            width: 300px;\r\n");
      out.write("            height: 170px;\r\n");
      out.write("            margin:auto;\r\n");
      out.write("        }\r\n");
      out.write("        .dd{\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("        .title{\r\n");
      out.write("        \ttext-indent: 25px;\r\n");
      out.write("        }\r\n");
      out.write("        .detailBtn{\r\n");
      out.write("        \tmargin:auto;\r\n");
      out.write("        }\r\n");
      out.write("        .resultSection{\r\n");
      out.write("        \theight:1400px;\r\n");
      out.write("        }\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body data-spy=\"scroll\" data-target=\"#templateux-navbar\" data-offset=\"200\">\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark pb_navbar pb_scrolled-light\" id=\"templateux-navbar\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\"><span class=\"text-danger\">Jeju</span>Boram</a>\r\n");
      out.write("        <div class=\"site-menu-toggle js-site-menu-toggle  ml-auto\"  data-aos=\"fade\" data-toggle=\"collapse\" data-target=\"#templateux-navbar-nav\" aria-controls=\"templateux-navbar-nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("              <span></span>\r\n");
      out.write("              <span></span>\r\n");
      out.write("              <span></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- END menu-toggle -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"templateux-navbar-nav\">\r\n");
      out.write("              <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#section-home\" id=\"nav1\">Home</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" target=\"_blank\" id=\"nav2\">Flight</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" target=\"_blank\" id=\"nav3\">RentCar</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#section-about\" id=\"nav4\">AboutJeju</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#section-team\" id=\"nav5\">Recommand</a></li>              \r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#section-menus\" id=\"nav6\">TourSpot</a></li>   \r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#section-events\" id=\"nav7\">JejuFestival</a></li>         \r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#section-contact\" id=\"nav8\">ContactUs</a></li>\r\n");
      out.write("                <!-- <li class=\"nav-item\"><a class=\"nav-link\" href=\"#section-apply\" id=\"nav9\">ApplyFor</a></li> -->\r\n");
      out.write("                <!-- <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\" id=\"join\">Join</a></li> -->\r\n");
      out.write("                <li class=\"nav-item cta-btn ml-xl-2 ml-lg-2 ml-md-0 ml-sm-0 ml-0\"><a class=\"nav-link\" id=\"loginBtn\" target=\"_blank\"><span class=\"pb_rounded-4 px-4 rounded\">Login</span></a></li>\r\n");
      out.write("                <li class=\"nav-item cta-btn ml-xl-2 ml-lg-2 ml-md-0 ml-sm-0 ml-0\"><a class=\"nav-link\" id=\"logoutBtn\" onclick=\"logout();\"><span class=\"pb_rounded-4 px-4 rounded\" >Logout</span></a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- Login Modal -->\r\n");
      out.write("    <div id=\"loginModal\" class=\"popModal\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <form class=\"form-login\" action=\"");
      out.print( request.getContextPath() );
      out.write("/login.me\" method=\"post\" onsubmit=\"return validate();\">\r\n");
      out.write("              <h2 class=\"form-login-heading\">sign in now</h2>\r\n");
      out.write("              <div class=\"login-wrap\">\r\n");
      out.write("                  <span class=\"close\">&times;</span>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" placeholder=\"User ID\" id=\"userId\" autofocus>\r\n");
      out.write("                <br>\r\n");
      out.write("                <input type=\"password\" class=\"form-control\" placeholder=\"Password\" id=\"userPwd\">\r\n");
      out.write("                <!-- <label class=\"checkbox\"> -->\r\n");
      out.write("                  <input type=\"checkbox\" value=\"remember-me\"> 기억하기\r\n");
      out.write("                  <span class=\"pull-right\">\r\n");
      out.write("                  <a data-toggle=\"modal\" href=\"header.jsp#myModal\"> Forgot Password?</a>\r\n");
      out.write("                  </span>\r\n");
      out.write("                  <!-- </label> -->\r\n");
      out.write("                <button class=\"btn btn-theme btn-block\" type=\"submit\"><a href=\"#\">SIGN IN</a></button>\r\n");
      out.write("                <hr>\r\n");
      out.write("                <div class=\"login-social-link centered\">\r\n");
      out.write("                  <p>or you can sign in via your social network</p>\r\n");
      out.write("                  <button class=\"btn btn-facebook\" type=\"submit\"><i class=\"fa fa-facebook\"></i> Facebook</button>\r\n");
      out.write("                  <button class=\"btn btn-twitter\" type=\"submit\"><i class=\"fa fa-twitter\"></i> Twitter</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"registration\">\r\n");
      out.write("                  Don't have an account yet?<br/>\r\n");
      out.write("                  <a class=\"\" href=\"#\">\r\n");
      out.write("                    Create an account\r\n");
      out.write("                    </a>\r\n");
      out.write("                <!-- </div> -->\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- Modal -->\r\n");
      out.write("              <div aria-hidden=\"true\" aria-labelledby=\"myModalLabel\" role=\"dialog\" tabindex=\"-1\" id=\"myModal\" class=\"modal fade\">\r\n");
      out.write("                <div class=\"modal-dialog\">\r\n");
      out.write("                  <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header\">\r\n");
      out.write("                      <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\r\n");
      out.write("                      <h4 class=\"modal-title\">Forgot Password ?</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-body\">\r\n");
      out.write("                      <p>Enter your e-mail address below to reset your password.</p>\r\n");
      out.write("                      <input type=\"text\" name=\"email\" placeholder=\"Email\" autocomplete=\"off\" class=\"form-control placeholder-no-fix\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-footer\">\r\n");
      out.write("                      <button data-dismiss=\"modal\" class=\"btn btn-default\" type=\"button\">Cancel</button>\r\n");
      out.write("                      <button class=\"btn btn-theme\" type=\"button\">Submit</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("              <!-- modal -->\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Flight Modal -->\r\n");
      out.write("    <div id=\"flightModal\" class=\"popModal\"> \r\n");
      out.write("      <!-- Modal content -->\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("          <span class=\"close\">&times;</span>\r\n");
      out.write("          <div\r\n");
      out.write("            data-skyscanner-widget=\"FlightSearchWidget\"\r\n");
      out.write("            data-locale=\"ko-KR\"\r\n");
      out.write("            data-market=\"KR\"\r\n");
      out.write("            data-currency=\"KRW\"\r\n");
      out.write("          ></div>\r\n");
      out.write("          <script src=\"https://widgets.skyscanner.net/widget-server/js/loader.js\" async></script>\r\n");
      out.write("      </div>   \r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("      <script>\r\n");
      out.write("          // loginModal\r\n");
      out.write("          var loginModal = document.getElementById('loginModal');\r\n");
      out.write("          var loginBtn = document.getElementById(\"loginBtn\");\r\n");
      out.write("   \r\n");
      out.write("          // flightModal\r\n");
      out.write("          var flightModal = document.getElementById('flightModal');\r\n");
      out.write("          var flight = document.getElementById(\"nav2\");\r\n");
      out.write("   \r\n");
      out.write("          // Get the <span> element that closes the modal\r\n");
      out.write("          var span = document.getElementsByClassName(\"close\");                                          \r\n");
      out.write("   \r\n");
      out.write("          // When the user clicks on the button, open the modal \r\n");
      out.write("          loginBtn.onclick = function() {\r\n");
      out.write("            loginModal.style.display = \"block\";\r\n");
      out.write("          } \r\n");
      out.write("          flight.onclick = function() {\r\n");
      out.write("            flightModal.style.display = \"block\";\r\n");
      out.write("          } \r\n");
      out.write("\r\n");
      out.write("          $(function(){\r\n");
      out.write("            // 모달창 x 버튼 누르면 창 꺼지기\r\n");
      out.write("            $(\".close\").click(function(){\r\n");
      out.write("              // console.log(\"sss\");\r\n");
      out.write("              $(this).parents(\".popModal\").css(\"display\", \"none\");\r\n");
      out.write("            });\r\n");
      out.write("          });\r\n");
      out.write("          \r\n");
      out.write("          function validate() {\r\n");
      out.write("  \t\t\tif($(\"#userId\").val().trim().length == 0){\t// 아이디 입력 안했을 경우\r\n");
      out.write("  \t\t\t\talert(\"아이디를 입력해주세요.\");\r\n");
      out.write("  \t\t\t\t$(\"#userId\").focus();\r\n");
      out.write("  \t\t\t\treturn false;\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  \t\t\tif($(\"#userPwd\").val().trim().length == 0){\t// 비밀번호 입력 안했을 경우\r\n");
      out.write("  \t\t\t\talert(\"비밀번호를 입력해주세요.\");\r\n");
      out.write("  \t\t\t\t$(\"#userPwd\").focus();\r\n");
      out.write("  \t\t\t\treturn false;\t\t\t\t\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t\t\t$(\"#loginBtn\").css('display','none');\r\n");
      out.write("  \t\t\t\t$(\"#logoutBtn\").css('display','block');\r\n");
      out.write("  \t\t\t\t\r\n");
      out.write("  \t\t\t\treturn true;\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("          \r\n");
      out.write("          \tfunction logout() {\r\n");
      out.write("  \t\t\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/logout.me\";\t\t\t\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("      </script> \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- END nav -->\r\n");
      out.write("\r\n");
      out.write("      <section class=\"site-hero overlay\" style=\"background-image: url(");
      out.print( request.getContextPath() );
      out.write("/resources/images/hero_5.jpg)\" data-stellar-background-ratio=\"0.5\" id=\"section-home\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row site-hero-inner justify-content-center align-items-center\">\r\n");
      out.write("            <div class=\"col-md-10 text-center\" data-aos=\"fade-up\">\r\n");
      out.write("              <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/jejuisland.png\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </section>\r\n");
      out.write("      <!-- END section -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <section class=\"section resultSection\" id=\"searchResult\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <aside>\r\n");
      out.write("            <hr>\r\n");
      out.write("              <label style=\"font-weight:bold\">숙소유형</label><br>\r\n");
      out.write("              <input type=\"checkbox\" id=\"hotel\"><label for=\"hotel\">호텔</label><br> \r\n");
      out.write("              <input type=\"checkbox\" id=\"resort\"><label for=\"resort\">리조트</label><br> \r\n");
      out.write("              <input type=\"checkbox\" id=\"condo\"><label for=\"condo\">콘도</label><br> \r\n");
      out.write("              <input type=\"checkbox\" id=\"hostel\"><label for=\"hostel\">호스텔</label><br> \r\n");
      out.write("              <input type=\"checkbox\" id=\"minbak\"><label for=\"minbak\">민박</label><br> \r\n");
      out.write("              \r\n");
      out.write("              <hr>\r\n");
      out.write("              \r\n");
      out.write("              <label style=\"font-weight:bold\">구역</label><br>\r\n");
      out.write("              <input type=\"checkbox\" id=\"jeju\"><label for=\"jeju\">제주시</label><br>\r\n");
      out.write("              <input type=\"checkbox\" id=\"seoguipo\"><label for=\"seoguipo\">서귀포시</label><br>\r\n");
      out.write("              \r\n");
      out.write("              <hr>\r\n");
      out.write("              \r\n");
      out.write("              <label style=\"font-weight:bold\">1박요금</label><br>\r\n");
      out.write("              <font size=2 id=\"minPrice_view\">최소가격 : &#8361;0</font><br>\r\n");
      out.write("              <input oninput='ShowSliderValueMin(this.value)' class=\"slide\" id=\"maxPrice\" type=\"range\" min='1' max='100' value='1' step=\"1\">\r\n");
      out.write("              <br>\r\n");
      out.write("              <font size=2 id=\"maxPrice_view\">최대가격 : &#8361;0</font><br>\r\n");
      out.write("              <input oninput='ShowSliderValueMax(this.value)' class=\"slide\" id=\"maxPrice\" type=\"range\" min='1' max='100' value='1' step=\"1\">\r\n");
      out.write("\r\n");
      out.write("              <script>\r\n");
      out.write("                  function ShowSliderValueMin(sVal){\r\n");
      out.write("\t                  var obValueView = document.getElementById(\"minPrice_view\");\r\n");
      out.write("                    if(sVal == '100'){\r\n");
      out.write("                      sVal = '1,00';\r\n");
      out.write("                      obValueView.innerHTML = \"최소가격 : &#8361;\"+sVal+\"0,000+\"\r\n");
      out.write("                    }else{\r\n");
      out.write("\t                    obValueView.innerHTML = \"최소가격 : &#8361;\"+sVal+\"0,000\"\r\n");
      out.write("                    }\r\n");
      out.write("                  }\r\n");
      out.write("                  function ShowSliderValueMax(sVal){\r\n");
      out.write("\t                  var obValueView = document.getElementById(\"maxPrice_view\");\r\n");
      out.write("                    if(sVal == '100'){\r\n");
      out.write("                      sVal = '1,00';\r\n");
      out.write("                      obValueView.innerHTML = \"최대가격 : &#8361;\"+sVal+\"0,000+\"\r\n");
      out.write("                    }else{\r\n");
      out.write("\t                    obValueView.innerHTML = \"최대가격 : &#8361;\"+sVal+\"0,000\"\r\n");
      out.write("                    }\r\n");
      out.write("                  }\r\n");
      out.write("              </script>\r\n");
      out.write("              <br>\r\n");
      out.write("              <hr>\r\n");
      out.write("              <label style=\"font-weight:bold\">등급</label><br>\r\n");
      out.write("              <input type=\"checkbox\" name=\"avgStar\" value=\"1\"><span class=\"star\"> ★★★★★</span><br>\r\n");
      out.write("              <input type=\"checkbox\" name=\"avgStar\" value=\"2\"><span class=\"star\"> ★★★★</span><br>\r\n");
      out.write("              <input type=\"checkbox\" name=\"avgStar\" value=\"3\"><span class=\"star\"> ★★★</span><br>\r\n");
      out.write("              <input type=\"checkbox\" name=\"avgStar\" value=\"4\"><span class=\"star\"> ★★</span><br>\r\n");
      out.write("              <input type=\"checkbox\" name=\"avgStar\" value=\"5\"><span class=\"star\"> ★</span><br>\r\n");
      out.write("              <hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          </aside>\r\n");
      out.write("          <div class=\"row justify-content-center mb-5\">\r\n");
      out.write("             \r\n");
      out.write("            <!-- <div class=\"result\" data-aos=\"fade-up\">     -->          \r\n");
      out.write("              <!-- <h2 class=\"heading\" data-aos=\"fade-up\">검색결과</h2> -->\r\n");
      out.write("              <!-- <div data-aos=\"fade-up\" data-aos-delay=\"100\" class=\"searchForm\" >검색된 숙소들 db에서 불러와서 여기에 뿌려주면 될듯?</div> -->\r\n");
      out.write("              <!-- <a href=\"#\" style=\"font-weight:bold; font-size: 1.5em;\">testHotel</a><br> -->\r\n");
      out.write("              \r\n");
      out.write("            <!-- </div> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"resultWrap\">\r\n");
      out.write("\t\t\t\t\t2019/00/00 ~ 2019/00/00 검색 결과\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"test resultWrap aa\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"test d1 dd aa\">\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"test d3 aa title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" style=\"font-weight:bold; font-size:1.5em;\">testHotel</a><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"test d4 aa\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"test dd d5 aa\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"test imgDiv aa\">썸네일</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"test dd d6\">설명</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"test d2 dd aa\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"test d7 aa\">가격</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"test d8 aa\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"detailBtn btn btn-primary btn-block text-white\" style=\"width:70%;\">상세보기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li><br>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"test resultWrap aa\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"test d1 dd aa\">\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"test d3 aa title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" style=\"font-weight:bold; font-size:1.5em;\">testHotel</a><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"test d4 aa\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"test dd d5 aa\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"test imgDiv aa\">썸네일</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"test dd d6\">설명</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"test d2 dd aa\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"test d7 aa\">가격</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"test d8 aa\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"detailBtn btn btn-primary btn-block text-white\" style=\"width:70%;\">상세보기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li><br>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"test resultWrap aa\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"test d1 dd aa\">\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"test d3 aa title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" style=\"font-weight:bold; font-size:1.5em;\">testHotel</a><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"test d4 aa\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"test dd d5 aa\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"test imgDiv aa\">썸네일</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"test dd d6\">설명</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"test d2 dd aa\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"test d7 aa\">가격</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"test d8 aa\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"detailBtn btn btn-primary btn-block text-white\" style=\"width:70%;\">상세보기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li><br>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"test resultWrap aa\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"test d1 dd aa\">\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"test d3 aa title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" style=\"font-weight:bold; font-size:1.5em;\">testHotel</a><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"test d4 aa\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"test dd d5 aa\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"test imgDiv aa\">썸네일</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"test dd d6\">설명</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"test d2 dd aa\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"test d7 aa\">가격</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"test d8 aa\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"detailBtn btn btn-primary btn-block text-white\" style=\"width:70%;\">상세보기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li><br>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>          \r\n");
      out.write("        </div>\r\n");
      out.write("      </section>\r\n");
      out.write("      \r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("\t<section class=\"section bg-image overlay\" style=\"background-image: url('");
      out.print( request.getContextPath() );
      out.write("/resources/images/hero_4.jpg');\" id=\"section-apply\">\r\n");
      out.write("        <div class=\"container\" >\r\n");
      out.write("          <div class=\"row align-items-center\">\r\n");
      out.write("            <div class=\"col-12 col-md-6 text-center mb-4 mb-md-0 text-md-left\" data-aos=\"fade-up\">\r\n");
      out.write("              <h2 class=\"text-white font-weight-bold\">제주에서 놀면서 일하실분!</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-12 col-md-6 text-center text-md-right\" data-aos=\"fade-up\" data-aos-delay=\"200\">\r\n");
      out.write("              <!-- Extra large modal -->\r\n");
      out.write("              <a href=\"#\" class=\"btn btn-outline-white-primary py-3 text-white px-5\" data-toggle=\"modal\" data-target=\"#reservation-form\">지금 지원하기</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer class=\"section footer-section\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row mb-4\">\r\n");
      out.write("            <div class=\"col-md-3 mb-5\">\r\n");
      out.write("              <ul class=\"list-unstyled link\">\r\n");
      out.write("                <li><a href=\"#\">About Us</a></li>\r\n");
      out.write("                <li><a href=\"#\">Terms &amp; Conditions</a></li>\r\n");
      out.write("                <li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("               <li><a href=\"#\">Rooms</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3 mb-5\">\r\n");
      out.write("              <ul class=\"list-unstyled link\">\r\n");
      out.write("                <li><a href=\"#\">The Rooms &amp; Suites</a></li>\r\n");
      out.write("                <li><a href=\"#\">About Us</a></li>\r\n");
      out.write("                <li><a href=\"#\">Contact Us</a></li>\r\n");
      out.write("                <li><a href=\"#\">Restaurant</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3 mb-5 pr-md-5 contact-info\">\r\n");
      out.write("              <!-- <li>198 West 21th Street, <br> Suite 721 New York NY 10016</li> -->\r\n");
      out.write("              <p><span class=\"d-block\"><span class=\"ion-ios-location h5 mr-3 text-primary\"></span>Address:</span> <span> 198 West 21th Street, <br> Suite 721 New York NY 10016</span></p>\r\n");
      out.write("              <p><span class=\"d-block\"><span class=\"ion-ios-telephone h5 mr-3 text-primary\"></span>Phone:</span> <span> (+1) 435 3533</span></p>\r\n");
      out.write("              <p><span class=\"d-block\"><span class=\"ion-ios-email h5 mr-3 text-primary\"></span>Email:</span> <span> info@yourdomain.com</span></p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3 mb-5\">\r\n");
      out.write("              <p>Sign up for our newsletter</p>\r\n");
      out.write("              <form action=\"#\" class=\"footer-newsletter\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <input type=\"email\" class=\"form-control\" placeholder=\"Email...\">\r\n");
      out.write("                  <button type=\"submit\" class=\"btn\"><span class=\"fa fa-paper-plane\"></span></button>\r\n");
      out.write("                </div>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"row pt-5\">\r\n");
      out.write("            <p class=\"col-md-8 text-left\">\r\n");
      out.write("              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart text-primary\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\" >Colorlib</a>\r\n");
      out.write("            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("            </p>\r\n");
      out.write("              \r\n");
      out.write("            <p class=\"col-md-4 text-right social\">\r\n");
      out.write("              <a href=\"#\"><span class=\"fa fa-tripadvisor\"></span></a>\r\n");
      out.write("              <a href=\"#\"><span class=\"fa fa-facebook\"></span></a>\r\n");
      out.write("              <a href=\"#\"><span class=\"fa fa-twitter\"></span></a>\r\n");
      out.write("              <a href=\"#\"><span class=\"fa fa-linkedin\"></span></a>\r\n");
      out.write("              <a href=\"#\"><span class=\"fa fa-vimeo\"></span></a>\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/js/popper.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/js/jquery.fancybox.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/js/jquery.easing.1.3.js\"></script>     \r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/js/aos.js\"></script>      \r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/js/bootstrap-datepicker.js\"></script> \r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/js/jquery.timepicker.min.js\"></script> \r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
